### ISSUE TITLE
vanilla playermodel apparently isn't hidden for others

### ISSUE THREAD

**Issue by unluckygardener** [H077y/minecraftslugcat#1]
no clue why this isn't working, but when i joined a server, apparently the vanilla model was hidden for me but not for anyone else. wish i knew more about coding this stuff so i could give more useful info, but i dont, sorry :(

**Comment by H077y** [comment]
Few questions to figure out what's going on:
1. What model are you using?
2. What version of Figura are you using?
3. What version of Figura are the other players using?
4. When the other players open the below menu and look at your name, is there a red dot? If yes, can they hover over it and say what the error says?
![image](https://github.com/H077y/minecraftslugcat/assets/64114013/a77084ee-d1f6-4614-9926-c68d5de16279)

**Comment by H077y** [comment]
[Resolved in Discord]
Non-client player using a version of Figura that's not supported by the model.
